version: "3"

services:
  dota_statistic_api:
    depends_on:
      - "database"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Local"
      
  database:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dota-bet-notes"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: