name: Frontend
run-name: Frontend
on:
  push:
    paths:
      - frontend
      - .github/workflows/frontend.yml
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - frontend
      - .github/workflows/frontend.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
